language: python

python:
  - '2.7'

before_install:
  - pip install nose
  - pip install coverage
  - pip install coveralls

install: pip install -r requirements.txt

script: make test

after_script: coveralls

notifications:
  email:
    recipients:
      - benjamin@bengfort.com
      - allen.leis@gmail.com
      - kostasxirog91@gmail.com
    on_success: change
    on_failure: always
